services:

  rabbitmq:
    image: rabbitmq:4-management
    container_name: ecommerce-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  postgres:
    image: postgres:17
    container_name: ecommerce-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ecommerce@123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  payment-service:
    build:
      context: ../Backend/Services/Payment
      dockerfile: PaymentService.API/Dockerfile
    container_name: ecommerce-payment

    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      order-service:
        condition: service_started
    ports:
      - "5005:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development

      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=ecommercepaymentdb;Username=postgres;Password=ecommerce@123"

      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: "AuthService"
      Jwt__Audience: "EcommercePlatform"

      InternalServices__ServiceKey: ${PAYMENT_SERVICE_KEY}

      Services__OrderService: "http://order-service:8080"

      InternalServices__OrderServiceKey: ${ORDER_SERVICE_KEY}

      RabbitMq__HostName: rabbitmq
      RabbitMq__UserName: guest
      RabbitMq__Password: guest

  notification-service:
    build:
      context: ../Backend/Services/Notification
      dockerfile: NotificationService.API/Dockerfile
    container_name: ecommerce-notification

    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    ports:
      - "5006:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development

      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=ecommercenotificationdb;Username=postgres;Password=ecommerce@123"

      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: "AuthService"
      Jwt__Audience: "EcommercePlatform"
  
      RabbitMq__HostName: rabbitmq
      RabbitMq__UserName: guest
      RabbitMq__Password: guest

      Email__From: ${EMAIL_FROM}
      Email__SmtpServer: ${EMAIL_SMTP_SERVER}
      Email__Port: ${EMAIL_PORT}
      Email__Username: ${EMAIL_USERNAME}
      Email__Password: ${EMAIL_PASSWORD}

  order-service:
    build:
      context: ../Backend/Services/Order
      dockerfile: OrderService.API/Dockerfile
    container_name: ecommerce-order

    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    ports:
      - "5007:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development

      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=ecommerceorderdb;Username=postgres;Password=ecommerce@123"

      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: "AuthService"
      Jwt__Audience: "EcommercePlatform"

      InternalServices__ServiceKey: ${ORDER_SERVICE_KEY}

      Services__ProductService: "http://product-service:8080"

      Services__InventoryService: "http://inventory-service:8080"

      RabbitMq__HostName: rabbitmq
      RabbitMq__UserName: guest
      RabbitMq__Password: guest

  product-service:
    build:
      context: ../Backend/Services/Product
      dockerfile: ProductService.API/Dockerfile
    container_name: ecommerce-product

    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    ports:
      - "5008:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development

      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=ecommerceproductdb;Username=postgres;Password=ecommerce@123"

      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: "AuthService"
      Jwt__Audience: "EcommercePlatform"

      InternalServices__ServiceKey: ${PRODUCT_SERVICE_KEY}

      RabbitMq__HostName: rabbitmq
      RabbitMq__UserName: guest
      RabbitMq__Password: guest

  inventory-service:
    build:
      context: ../Backend/Services/Inventory
      dockerfile: InventoryService.API/Dockerfile
    container_name: ecommerce-inventory

    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    ports:
      - "5009:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development

      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=ecommerceinventorydb;Username=postgres;Password=ecommerce@123"

      InternalServices__ServiceKey: ${INVENTORY_SERVICE_KEY}

      RabbitMq__HostName: rabbitmq
      RabbitMq__UserName: guest
      RabbitMq__Password: guest
  
  auth-service:
    build:
      context: ../Backend/Services/Auth
      dockerfile: AuthService.API/Dockerfile

    container_name: ecommerce-auth

    depends_on:
      - postgres

    ports:
      - "5001:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Development

      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=ecommerceauthdb;Username=postgres;Password=ecommerce@123"

      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: "AuthService"
      Jwt__Audience: "EcommercePlatform"
      Jwt__ExpirationMinutes: 60
      Jwt__RefreshTokenExpirationDays: 7

      DevelopmentAdmin__FirstName: "System"
      DevelopmentAdmin__LastName: "Admin"
      DevelopmentAdmin__Email: ${ADMIN_EMAIL}
      DevelopmentAdmin__Password: ${ADMIN_PASSWORD}

volumes:
  rabbitmq_data:
  postgres_data: